[[handler]]
type = "image"
origin = "goes19"
directory = "/srv/goes/goes19/{region:short|lower}/{channel:short|lower}/{time:%Y-%m-%d}"
filename = "GOES19_{region:short}_{channel:short}_{time:%Y%m%dT%H%M%SZ}"
format = "jpg"
json = false
  [[handler.map]]
  path = "/usr/local/share/goestools/ne/ne_50m_admin_0_countries_lakes.json"
  [[handler.map]]
  path = "/usr/local/share/goestools/ne/ne_50m_admin_1_states_provinces_lakes.json"

[[handler]]
type = "emwin"
directory = "/srv/goes/emwin/{time:%Y-%m-%d}"

[[handler]]
type = "text"
origin = "nws"
directory = "/srv/goes/text/nws/{time:%Y-%m-%d}"

[[handler]]
type = "text"
origin = "other"
directory = "/srv/goes/text/other/{time:%Y-%m-%d}"
